### ISSUE TITLE
Some LUTs are missing

### ISSUE THREAD

**Issue by ndefrancesco** [cleterrier/ChrisLUTs#1]
Hi @cleterrier!

I was perusing the excellent LUT collection, and stumbled upon some scripts that are failing to load:
```javascript
run("Matter ");
run("cividis ");
run("oslo "); // it's misspelled as "olso" inside the script
```
I made sure that this list is extensive, by checking the whole collection with the following script. It might come handy for maintaining the collection:
```javascript
List.setCommands;
List.toArrays(keys, values);
for (i = 0; i < List.size; i++) {
	if(indexOf(values[i], "script:LUTs/")>-1){
		if(keys[i] != "About LUTs") {
			// when encountering an error, you can take note and continue by pressing "ok"
			run(keys[i]);
			}
		}
	}
showMessage("done");
```
Thanks for taking the time to create this great addition to Fiji!
Cheers!
Nico

**Comment by cleterrier** [comment]
Hi, thanks for the script! I solved the current problems - this meant replacing Fiji's built-in civis LUT which is not recognized as a LUT (values are normalized between 0-1 rather than 0-255). Let me know if there are any other problems
